package kfl.ctrl;

/*
 * Find.java
 *
 * Created on 01. Februar 2002, 14:25
 */

/**
 *
 * @author  Standard
 */
import BBSys;
import Msg;

public class SetAddress extends javax.swing.JFrame {

	private boolean exit = false;
	private Msg m;

	/** Creates new form Find */
	public SetAddress(Msg m, int a) {
		this.m = m;
		initComponents();
		txtOldAddress.setText(""+a);
	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void initComponents() {//GEN-BEGIN:initComponents
            jButton1 = new javax.swing.JButton();
            jPanel1 = new javax.swing.JPanel();
            jLabel3 = new javax.swing.JLabel();
            txtOldAddress = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            txtNewAddress = new javax.swing.JTextField();
            jPanel2 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            txtLog = new javax.swing.JTextField();
            
            setTitle("Find Stations");
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
            
            jButton1.setText("Set");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            
            getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);
            
            jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
            
            jLabel3.setText("old Address:");
            jPanel1.add(jLabel3);
            
            txtOldAddress.setColumns(3);
            txtOldAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jPanel1.add(txtOldAddress);
            
            jLabel1.setText("new Address:");
            jPanel1.add(jLabel1);
            
            txtNewAddress.setColumns(3);
            txtNewAddress.setText("1");
            txtNewAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jPanel1.add(txtNewAddress);
            
            getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);
            
            jLabel2.setText("Status:");
            jPanel2.add(jLabel2);
            
            txtLog.setColumns(10);
            jPanel2.add(txtLog);
            
            getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
            
            pack();
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            setSize(new java.awt.Dimension(300, 200));
            setLocation((screenSize.width-300)/2,(screenSize.height-200)/2);
        }//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// Add your handling code here:
		txtLog.setText("");
		int newAddr = Integer.parseInt(txtNewAddress.getText());
		int oldAddr = Integer.parseInt(txtOldAddress.getText());
		m.exchg(oldAddr, BBSys.CMD_SET_STATE, BBSys.MS_DBG);
		int val = m.exchg(oldAddr, BBSys.CMD_SETAD, newAddr);
		if (val<0) {
			m.clear();
			txtLog.setText("Fehler "+val);
		} else {
			txtLog.setText("OK");
			txtOldAddress.setText(""+newAddr);
		}
	}//GEN-LAST:event_jButton1ActionPerformed

	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		if (exit) {
			System.exit(0);
		} else {
			dispose();
		}
	}//GEN-LAST:event_exitForm

	public static void main(String args[]) {
		Msg m = new Msg();
		SetAddress f = new SetAddress(m, 0);
		f.exit = true;
		f.show();
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtOldAddress;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JTextField txtNewAddress;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JTextField txtLog;
        // End of variables declaration//GEN-END:variables

}
