/* AUTOGENERATED from com.jopdesign.tools.Instruction */
/* CAVEAT: Do not change manually */

package com.jopdesign.timing.jop;
public class MicrocodeConstants {
  public static final int POP             = 0x0; /* consumer */ 
  public static final int AND             = 0x1; /* consumer */ 
  public static final int OR              = 0x2; /* consumer */ 
  public static final int XOR             = 0x3; /* consumer */ 
  public static final int ADD             = 0x4; /* consumer */ 
  public static final int SUB             = 0x5; /* consumer */ 
  public static final int ST0             = 0x10; /* consumer */ 
  public static final int ST1             = 0x11; /* consumer */ 
  public static final int ST2             = 0x12; /* consumer */ 
  public static final int ST3             = 0x13; /* consumer */ 
  public static final int ST              = 0x14; /* consumer */ 
  public static final int STMI            = 0x15; /* consumer */ 
  public static final int STVP            = 0x18; /* consumer */ 
  public static final int STJPC           = 0x19; /* consumer */ 
  public static final int STAR            = 0x1a; /* consumer */ 
  public static final int STSP            = 0x1b; /* consumer */ 
  public static final int USHR            = 0x1c; /* consumer */ 
  public static final int SHL             = 0x1d; /* consumer */ 
  public static final int SHR             = 0x1e; /* consumer */ 
  public static final int STM             = 0x20; /* consumer opd MS: not to confuse it with opd in mc*/ 
  public static final int STMUL           = 0x40; /* consumer */ 
  public static final int STMWA           = 0x41; /* consumer */ 
  public static final int STMRA           = 0x42; /* consumer */ 
  public static final int STMWD           = 0x43; /* consumer */ 
  public static final int STALD           = 0x44; /* consumer */ 
  public static final int STAST           = 0x45; /* consumer */ 
  public static final int STGF            = 0x46; /* consumer */ 
  public static final int STPF            = 0x47; /* consumer */ 
  public static final int STCP            = 0x48; /* consumer */ 
  public static final int STBCRD          = 0x49; /* consumer */ 
  public static final int STIDX           = 0x4a; /* consumer */ 
  public static final int STPS            = 0x4b; /* consumer */ 
  public static final int STMRAC          = 0x4c; /* consumer */ 
  public static final int STMRAF          = 0x4d; /* consumer */ 
  public static final int STMWDF          = 0x4e; /* consumer */ 
  public static final int LDM             = 0xa0; /* producer opd MS: not to confuse it with opd in mc*/ 
  public static final int LDI             = 0xc0; /* producer opd MS: not to confuse it with opd in mc*/ 
  public static final int LDMRD           = 0xe0; /* producer */ 
  public static final int LDMUL           = 0xe1; /* producer */ 
  public static final int LDBCSTART       = 0xe2; /* producer */ 
  public static final int LD0             = 0xe8; /* producer */ 
  public static final int LD1             = 0xe9; /* producer */ 
  public static final int LD2             = 0xea; /* producer */ 
  public static final int LD3             = 0xeb; /* producer */ 
  public static final int LD              = 0xec; /* producer */ 
  public static final int LDMI            = 0xed; /* producer */ 
  public static final int LDSP            = 0xf0; /* producer */ 
  public static final int LDVP            = 0xf1; /* producer */ 
  public static final int LDJPC           = 0xf2; /* producer */ 
  public static final int LD_OPD_8U       = 0xf4; /* producer */ 
  public static final int LD_OPD_8S       = 0xf5; /* producer */ 
  public static final int LD_OPD_16U      = 0xf6; /* producer */ 
  public static final int LD_OPD_16S      = 0xf7; /* producer */ 
  public static final int DUP             = 0xf8; /* producer */ 
  public static final int NOP             = 0x100; /* nostack */ 
  public static final int WAIT            = 0x101; /* nostack */ 
  public static final int JBR             = 0x102; /* nostack */ 
  public static final int STGS            = 0x110; /* nostack */ 
  public static final int BZ              = 0x180; /* consumer opd MS: not to confuse it with opd in mcjmp */ 
  public static final int BNZ             = 0x1c0; /* consumer opd MS: not to confuse it with opd in mcjmp */ 
  public static final int JMP             = 0x200; /* nostack opd MS: not to confuse it with opd in mcjmp */ 
};