#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"
source "${DIR}/wcet.sh"

# SuperGraph1
export P1=test;export P2=wcet/devel;export P3=SuperGraph1
echo "[SuperGraph1] $(logfile '$KEY')" >&2

make_java
make_sim jsim 2079873
make_wcet cs-0-dfa-yes 67370795 CALLSTRING_LENGTH=0 USE_DFA=yes
make_wcet cs-1-dfa-yes  2524044 CALLSTRING_LENGTH=1 USE_DFA=yes
make_wcet cs-2-dfa-yes  2079945 CALLSTRING_LENGTH=2 USE_DFA=yes
