#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"
source "${DIR}/wcet.sh"

# Rasmus
export P1=test;export P2=wcet/devel;export P3=Rasmus
echo "[Rasmus] $(logfile '$KEY')" >&2

make_java
make_sim jsim 1035
make_wcet cs-0-dfa-no  1078 CALLSTRING_LENGTH=0 USE_DFA=no
make_wcet cs-2-dfa-yes 1078 CALLSTRING_LENGTH=2 USE_DFA=yes
