#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"
source "${DIR}/wcet.sh"

# StartLift
export P1=test;export P2=wcet;export P3=StartLift
echo "[Lift] $(logfile '$KEY')" >&2
make_sim jsim 5007
make_java
make_wcet cs-0-dfa-no 7621 CALLSTRING_LENGTH=0 USE_DFA=no
make_wcet cs-0-dfa-yes 7621 CALLSTRING_LENGTH=0 USE_DFA=yes
make_wcet cs-1-dfa-yes 7621 CALLSTRING_LENGTH=1 USE_DFA=yes

