
# 
#  Generated file - virtual lab module
#  DO NOT MODIFY THIS GENERATED FILE.
#  
ERR_TABLE = {}
ERR_NOUART = "nouart"
ERR_TABLE[ ERR_NOUART ] = "Requested UART does not exist."
ERR_BADBAUD = "badbaud"
ERR_TABLE[ ERR_BADBAUD ] = "Requested baud rate is not supported by the hardware."
ERR_BUSY = "busy"
ERR_TABLE[ ERR_BUSY ] = "Requested FPGA board is busy - too many connections."
ERR_COMMAND = "command"
ERR_TABLE[ ERR_COMMAND ] = "Unsupported command."
ERR_UNKNOWN = "unknown"
ERR_TABLE[ ERR_UNKNOWN ] = "Unknown error."
ERR_DISCONNECT = "disconnect"
ERR_TABLE[ ERR_DISCONNECT ] = "Disconnected."
ERR_UNKNOWNBOARD = "unknownboard"
ERR_TABLE[ ERR_UNKNOWNBOARD ] = "Unknown FPGA board requested."
ERR_UNAVAILABLE = "unavailable"
ERR_TABLE[ ERR_UNAVAILABLE ] = "Requested FPGA board is not online."
ERR_CONFIG = "config"
ERR_TABLE[ ERR_CONFIG ] = "Server configuration error."
ERR_NONE = "none"
ERR_TABLE[ ERR_NONE ] = "No error."
ERR_NORESP = "noresp"
ERR_TABLE[ ERR_NORESP ] = "No response."
ERR_PARSEBITS = "parsebits"
ERR_TABLE[ ERR_PARSEBITS ] = "Unable to parse bit file header."
ERR_DONENOTHIGH = "donenothigh"
ERR_TABLE[ ERR_DONENOTHIGH ] = "DONE pin did not go high."
ERR_IDFAILED = "idfailed"
ERR_TABLE[ ERR_IDFAILED ] = "Reading IDCODE from FPGA failed."
ERR_WRONGDRIVER = "wrongdriver"
ERR_TABLE[ ERR_WRONGDRIVER ] = "IDCODE not recognised by the driver: FPGA not supported."
ERR_BADSIZE = "badsize"
ERR_TABLE[ ERR_BADSIZE ] = "Number of bytes is not valid for this FPGA."
ERR_ALLOC = "alloc"
ERR_TABLE[ ERR_ALLOC ] = "Unable to allocate a buffer for this bitfile."
ERR_DENIED = "denied"
ERR_TABLE[ ERR_DENIED ] = "Bitfile id (BID) is not valid: programming is denied."
ERR_PQFULL = "pqfull"
ERR_TABLE[ ERR_PQFULL ] = "Programming queue is full."
ERR_NOSPACE = "nospace"
ERR_TABLE[ ERR_NOSPACE ] = "There is no space for new bitfiles."
ERR_TDOMISMATCH = "tdomismatch"
ERR_TABLE[ ERR_TDOMISMATCH ] = "TDO readback mismatch during XSVF playback: FPGA disconnected?"
ERR_XSVFERROR = "xsvferror"
ERR_TABLE[ ERR_XSVFERROR ] = "Error in XSVF file."
ERR_PERMISSION = "permission"
ERR_TABLE[ ERR_PERMISSION ] = "Board access denied."
ERR_NOSETUID = "nosetuid"
ERR_TABLE[ ERR_NOSETUID ] = "Use the setuid command first."
ERR_ALREADYLOCKED = "alreadylocked"
ERR_TABLE[ ERR_ALREADYLOCKED ] = "You already hold a lock."
ERR_NOMUTEXDAEMON = "nomutexdaemon"
ERR_TABLE[ ERR_NOMUTEXDAEMON ] = "The mutual exclusion daemon is not running."
