md actel\jop\hdl
copy /V /Y vhdl\top\jop_a3p.vhd		actel\jop\hdl\
copy /V /Y vhdl\top\jop_config_a3p.vhd	actel\jop\hdl\
copy /V /Y vhdl\actel\actelram.vhd	actel\jop\hdl\
copy /V /Y vhdl\core\bcfetch.vhd	actel\jop\hdl\
copy /V /Y vhdl\core\cache.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\core.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\decode.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\extension.vhd	actel\jop\hdl\
copy /V /Y vhdl\core\fetch.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\jop_types.vhd	actel\jop\hdl\
copy /V /Y vhdl\core\jopcpu.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\mul.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\shift.vhd		actel\jop\hdl\
copy /V /Y vhdl\core\stack.vhd		actel\jop\hdl\
copy /V /Y vhdl\scio\fifo.vhd		actel\jop\hdl\
copy /V /Y vhdl\memory\mem_sc.vhd	actel\jop\hdl\
copy /V /Y vhdl\memory\jbc_generic.vhd	actel\jop\hdl\
copy /V /Y vhdl\memory\sc_sram32.vhd	actel\jop\hdl\
copy /V /Y vhdl\simpcon\sc_pack.vhd	actel\jop\hdl\
copy /V /Y vhdl\scio\sc_sys.vhd		actel\jop\hdl\
copy /V /Y vhdl\scio\sc_uart.vhd	actel\jop\hdl\
copy /V /Y vhdl\scio\scio_min.vhd	actel\jop\hdl\
copy /V /Y vhdl\actelram_initrom.vhd	actel\jop\hdl\
copy /V /Y vhdl\jtbl.vhd		actel\jop\hdl\
copy /V /Y vhdl\offtbl.vhd		actel\jop\hdl\
copy /V /Y vhdl\rom.vhd			actel\jop\hdl\
