#!/bin/sh

export NAME=ml401
export PART=xc4vlx25-ff668-10

if test -z "$XILINX"
then
    echo '$XILINX variable not set!'
    exit 1
fi

python mkchain.py || exit 1
pushd ../../vhdl/jeopard || exit 1
python build.py || exit 1
popd

rm -rf out
mkdir out out/tmp || exit 1
xst -intstyle ise -ifn ${NAME}.xst \
        -ofn out/${NAME}.syr || exit 1
ngdbuild -intstyle ise -dd out/_ngo -uc ${NAME}.ucf \
        -p ${PART} out/${NAME}.ngc out/${NAME}.ngd || exit 1
map -intstyle ise -p ${PART} -cm area -pr b -k 4 -c 100 -tx off \
        -o out/${NAME}_map.ncd out/${NAME}.ngd out/${NAME}.pcf || exit 1
par -w -intstyle ise -ol std -t 1 out/${NAME}_map.ncd \
        out/${NAME}.ncd out/${NAME}.pcf || exit 1
trce -intstyle ise -e 3 -l 3 -xml out/${NAME} \
        out/${NAME}.ncd -o out/${NAME}.twr out/${NAME}.pcf || exit 1
bitgen -intstyle ise -f ${NAME}.ut out/${NAME}.ncd || exit 1
cp out/${NAME}.bit . || exit 1


