add(Write(output_name="break_command", size=3))
add(Read(input_name="cc_out_data", size=32))
add(Read(input_name="cc_out_wr", size=0))
add(Read(input_name="cc_out_rdy", size=0))
add(Read(input_name="cc_in_data", size=32))
add(Read(input_name="cc_in_wr", size=0))
add(Read(input_name="cc_in_rdy", size=0))
add(Read(input_name="breakpoint", size=0))
add(Read(input_name="terminal", size=0))
add(Read(input_name="start", size=0))
add(Read(input_name="busy", size=0))
add(Read(input_name="grab", size=0))
add(Read(input_name="running", size=0))
add(Read(input_name="reading", size=0))

add(Read(input_name="sc_arb_out_0_rd", size=0))
add(Read(input_name="sc_arb_out_0_wr", size=0))
add(Read(input_name="sc_arb_out_0_wr_data", size=32))
add(Read(input_name="sc_arb_out_0_atomic", size=0))
add(Read(input_name="sc_arb_out_0_address", size=24))
add(Read(input_name="sc_arb_in_0_rd_data", size=32))
add(Read(input_name="sc_arb_in_0_rdy_cnt", size=2))
add(Read(input_name="sc_arb_out_1_rd", size=0))
add(Read(input_name="sc_arb_out_1_wr", size=0))
add(Read(input_name="sc_arb_out_1_wr_data", size=32))
add(Read(input_name="sc_arb_out_1_atomic", size=0))
add(Read(input_name="sc_arb_out_1_address", size=24))
add(Read(input_name="sc_arb_in_1_rd_data", size=32))
add(Read(input_name="sc_arb_in_1_rdy_cnt", size=2))
add(Read(input_name="sc_mem_out_rd", size=0))
add(Read(input_name="sc_mem_out_wr", size=0))
add(Read(input_name="sc_mem_out_wr_data", size=32))
add(Read(input_name="sc_mem_out_atomic", size=0))
add(Read(input_name="sc_mem_out_address", size=24))
add(Read(input_name="sc_mem_in_rd_data", size=32))
add(Read(input_name="sc_mem_in_rdy_cnt", size=2))


